language: node_js

node_js:
- 6
- stable

before_install:
- yarn global add codecov

script:
- yarn run lint
- yarn run test

- yarn upgrade @angular/compiler@8.0.0
- node -e "assert.equal(require('@angular/compiler').VERSION.full, '8.0.0')"
- yarn run test

- yarn upgrade @angular/compiler@7
- node -e "assert.equal(require('@angular/compiler').VERSION.major, '7')"
- yarn run test

- yarn upgrade @angular/compiler@6
- node -e "assert.equal(require('@angular/compiler').VERSION.major, '6')"
- yarn run test

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
