language: node_js

node_js:
- 6
- stable

before_install:
- yarn global add codecov

script:
- node -e "assert.ok(!/^(?:[67]|8\.[01])\./.test(require('@angular/compiler').VERSION.full))"
- yarn run lint
- yarn run test

- yarn upgrade @angular/compiler@8.1
- node -e "assert.equal(require('@angular/compiler').VERSION.full.slice(0, 4), '8.1.')"
- yarn run test

- yarn upgrade @angular/compiler@7
- node -e "assert.equal(require('@angular/compiler').VERSION.major, '7')"
- yarn run test

- yarn upgrade @angular/compiler@6
- node -e "assert.equal(require('@angular/compiler').VERSION.major, '6')"
- yarn run test

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
