language: node_js

node_js:
- 10.13.0
- stable

before_install:
- yarn global add codecov

script:
- yarn run lint
- ENABLE_COVERAGE=1 yarn run test

- yarn upgrade @angular/compiler@^9.1.0
- yarn run test

- yarn upgrade @angular/compiler@~10.0.0
- yarn run test

- yarn upgrade @angular/compiler@~10.1.0
- yarn run test

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
