language: node_js

node_js:
- 6
- stable

before_install:
- yarn global add codecov

script:
- node -p "require('@angular/compiler/package.json').version"
- yarn run lint
- yarn run test

- yarn upgrade @angular/compiler@7
- node -p "require('@angular/compiler/package.json').version"
- yarn run test

- yarn upgrade @angular/compiler@6
- node -p "require('@angular/compiler/package.json').version"
- yarn run test

after_script:
- codecov

matrix:
  fast_finish: true
