name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        node:
          - "14"
          - "10.13.0"
        angular:
          - ""
          - "^9.1.0"
          - "~10.0.0"
          - "^10.1.0"
    name: Node.js ${{ matrix.node }} / angular ${{ matrix.angular }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
      - if: matrix.angular != ''
        run: yarn upgrade @angular/compiler@${{ matrix.angular }}
      - run: yarn run test
        env:
          ENABLE_COVERAGE: ${{ matrix.angular == '' && '1' || '' }}
      - run: npx codecov
